spring.application.name=expense-subscription-tracker-service
# --- Supabase Veritaban? Ayarlar? ---

# Spring Boot için URL'in ba??nda 'jdbc:' olmas? gerekir.
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres

# Kullan?c? ad? (Connection string'den al?nd?)
spring.datasource.username=postgres.obrqcxurldvvnseciehb

# BURAYA veritaban? ?ifrenizi yaz?n (Kö?eli parantezleri silin)
spring.datasource.password=04603As312+

# Sürücü ve Dialect Ayarlar?
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Veritaban? tablolar?n? otomatik güncelleme ayar?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SSL Modu (Supabase ba?lant?s? için gerekli olabilir)
spring.datasource.hikari.data-source-properties.sslMode=require
# Swagger UI yolunu de?i?tirmek için (Örn: /swagger-ui.html yerine /belgeler)
springdoc.swagger-ui.path=/swagger-ui.html

server.port=1881